// Every piece of static interface text, in English, Azerbaijani and Russian (in that order).
// Text that the server writes about one specific invoice (the calculation, the reason a rule
// was broken, an auditor's comment) is data, not interface text, and is shown as written.

export type Lang = "en" | "az" | "ru";
export const LANGS: { id: Lang; label: string; name: string; locale: string }[] = [
  { id: "az", label: "AZ", name: "Azərbaycan dili", locale: "az-AZ" },
  { id: "en", label: "EN", name: "English", locale: "en-GB" },
  { id: "ru", label: "RU", name: "Русский", locale: "ru-RU" },
];

type Row = [en: string, az: string, ru: string];

export const DICT: Record<string, Row> = {
  // ---------------------------------------------------------------- shared
  "nav.submit": ["Submit an invoice", "Faktura göndər", "Отправить счёт"],
  "nav.my": ["My invoices", "Fakturalarım", "Мои счета"],
  "nav.audit": ["Audit desk", "Audit masası", "Стол аудита"],
  "nav.overview": ["Overview", "Ümumi hesabat", "Общий отчёт"],
  "nav.accounts": ["Accounts", "Hesablar", "Учётные записи"],
  "nav.check": ["Quick check", "Sürətli yoxlama", "Быстрая проверка"],
  "nav.signin": ["Sign in", "Daxil ol", "Войти"],
  "nav.signout": ["Sign out", "Çıxış", "Выйти"],
  "nav.pending": ["Auditor access pending", "Auditor girişi təsdiq gözləyir", "Доступ аудитора ожидает подтверждения"],
  "nav.account": ["Your account", "Hesabınız", "Ваша учётная запись"],
  "nav.language": ["Language", "Dil", "Язык"],
  "nav.new_alerts": ["{n} new alerts", "{n} yeni xəbərdarlıq", "Новых оповещений: {n}"],
  "nav.waiting": ["{n} waiting for approval", "{n} nəfər təsdiq gözləyir", "Ожидают подтверждения: {n}"],
  "nav.home": ["FiscalAI home", "FiscalAI ana səhifə", "FiscalAI, главная"],
  "nav.main": ["Main", "Əsas menyu", "Главное меню"],
  "skip": ["Skip to content", "Məzmuna keç", "Перейти к содержимому"],

  "role.employee": ["Employee", "İşçi", "Сотрудник"],
  "role.auditor": ["Auditor", "Auditor", "Аудитор"],
  "role.admin": ["Admin", "Admin", "Админ"],

  "status.approved": ["Approved", "Təsdiqləndi", "Одобрен"],
  "status.flagged": ["Flagged", "Qayda pozuntusu", "Нарушение"],
  "status.needs_review": ["Needs review", "Yoxlama lazımdır", "Нужна проверка"],

  "stamp.approved": ["Approved", "Təsdiqləndi", "Одобрено"],
  "stamp.flagged": ["Flagged", "Pozuntu", "Нарушение"],
  "stamp.needs_review": ["Needs review", "Yoxlanmalı", "На проверку"],
  "stamp.paid": ["Cleared to pay", "Ödənişə buraxıldı", "К оплате"],
  "stamp.rejected": ["Rejected", "Rədd edildi", "Отклонено"],
  "stamp.duplicate": ["Duplicate", "Dublikat", "Дубликат"],
  "stamp.sent_to_audit": ["Sent to audit", "Auditə göndərildi", "Передано аудиту"],
  "stamp.cleared": ["Cleared", "Keçdi", "Принято"],
  "stamp.not_accepted": ["Not accepted", "Qəbul edilmədi", "Не принято"],

  "common.checking": ["Checking your sign-in…", "Girişiniz yoxlanılır…", "Проверяем вход…"],
  "common.cancel": ["Cancel", "Ləğv et", "Отмена"],
  "common.open": ["Open", "Aç", "Открыть"],
  "common.dismiss": ["Dismiss", "Bağla", "Закрыть"],
  "common.hide": ["Hide", "Gizlət", "Скрыть"],
  "common.show": ["Show", "Göstər", "Показать"],
  "common.error": ["Something went wrong.", "Xəta baş verdi.", "Произошла ошибка."],
  "common.no_server": [
    "FiscalAI's server can't be reached. Check that the backend is running.",
    "FiscalAI serverinə qoşulmaq olmur. Backend-in işlədiyini yoxlayın.",
    "Сервер FiscalAI недоступен. Проверьте, что backend запущен.",
  ],
  "common.request_failed": ["Request failed ({n}).", "Sorğu alınmadı ({n}).", "Запрос не выполнен ({n})."],
  "common.an_auditor": ["an auditor", "auditor", "аудитор"],
  "common.unreadable": ["amount unreadable", "məbləğ oxunmadı", "сумма не прочитана"],
  "common.unknown_vendor": ["Unknown vendor", "Naməlum satıcı", "Неизвестный поставщик"],

  "footer.policy": [
    "FiscalAI checks invoices against the Nordvik Holdings expense policy.",
    "FiscalAI fakturaları Nordvik Holdings xərc siyasətinə görə yoxlayır.",
    "FiscalAI проверяет счета по политике расходов Nordvik Holdings.",
  ],
  "footer.principle": [
    "The AI reads the document; the policy rules decide.",
    "Sənədi AI oxuyur; qərarı siyasət qaydaları verir.",
    "Документ читает ИИ; решение принимают правила политики.",
  ],

  "time.now": ["just now", "indicə", "только что"],
  "time.min": ["{n} min ago", "{n} dəq əvvəl", "{n} мин назад"],
  "time.hour": ["{n} h ago", "{n} saat əvvəl", "{n} ч назад"],

  "guard.wait_title": ["Waiting for the admin", "Admin təsdiqi gözlənilir", "Ожидается подтверждение админа"],
  "guard.wait_body": [
    "You registered as an auditor. The FiscalAI admin has to approve that before you can see other people's invoices. This page opens by itself once they do; until then you can submit your own.",
    "Siz auditor kimi qeydiyyatdan keçmisiniz. Başqalarının fakturalarını görməyiniz üçün FiscalAI admini bunu təsdiqləməlidir. Təsdiqdən sonra bu səhifə özü açılacaq; o vaxta qədər öz fakturalarınızı göndərə bilərsiniz.",
    "Вы зарегистрировались как аудитор. Прежде чем вы увидите чужие счета, админ FiscalAI должен это подтвердить. После подтверждения страница откроется сама; пока вы можете отправлять свои счета.",
  ],
  "guard.no_title": ["This page is for the audit team", "Bu səhifə audit komandası üçündür", "Эта страница для команды аудита"],
  "guard.no_body": [
    "You are signed in as {name} ({role}). Ask the FiscalAI admin if you need access.",
    "Siz {name} ({role}) kimi daxil olmusunuz. Giriş lazımdırsa, FiscalAI admininə müraciət edin.",
    "Вы вошли как {name} ({role}). Если нужен доступ, обратитесь к админу FiscalAI.",
  ],

  // ---------------------------------------------------------------- sign-in and registration
  "login.side_employee": ["Employee", "İşçi", "Сотрудник"],
  "login.side_auditor": ["Audit team", "Audit komandası", "Команда аудита"],
  "login.sides": ["Which side of FiscalAI", "FiscalAI-nin hansı tərəfi", "Какая сторона FiscalAI"],
  "login.does_employee": [
    "Submit your invoices and receipts and follow what happens to them.",
    "Faktura və qəbzlərinizi göndərin və onların vəziyyətini izləyin.",
    "Отправляйте свои счета и чеки и следите за их статусом.",
  ],
  "login.does_auditor": [
    "Review submitted invoices, clear or reject them, and see the overall picture.",
    "Göndərilən fakturaları yoxlayın, təsdiqləyin və ya rədd edin, ümumi mənzərəni görün.",
    "Проверяйте отправленные счета, одобряйте или отклоняйте их и смотрите общую картину.",
  ],
  "login.signin_employee": ["Employee sign-in", "İşçi girişi", "Вход для сотрудника"],
  "login.signin_auditor": ["Audit team sign-in", "Audit komandası girişi", "Вход для аудита"],
  "login.register_employee": ["Register as an employee", "İşçi kimi qeydiyyat", "Регистрация сотрудника"],
  "login.register_auditor": ["Register as an auditor", "Auditor kimi qeydiyyat", "Регистрация аудитора"],
  "login.setup_title": ["Set up FiscalAI", "FiscalAI-ni quraşdır", "Настройка FiscalAI"],
  "login.setup_body": [
    "FiscalAI has no admin yet. Create the admin account: the one person who manages everyone else's access.",
    "FiscalAI-da hələ admin yoxdur. Admin hesabını yaradın: hamının girişini idarə edən tək şəxs.",
    "В FiscalAI пока нет админа. Создайте учётную запись админа: единственного человека, который управляет доступом остальных.",
  ],
  "login.approval_notice": [
    "Auditors can clear invoices for payment, so the FiscalAI admin confirms each auditor. Until they do, your account works as an employee account.",
    "Auditorlar fakturaları ödənişə buraxa bilir, ona görə hər auditoru FiscalAI admini təsdiqləyir. Təsdiqə qədər hesabınız işçi hesabı kimi işləyəcək.",
    "Аудиторы могут допускать счета к оплате, поэтому каждого аудитора подтверждает админ FiscalAI. До подтверждения учётная запись работает как запись сотрудника.",
  ],
  "login.name": ["Full name", "Ad və soyad", "Имя и фамилия"],
  "login.email": ["Work email", "İş e-poçtu", "Рабочая почта"],
  "login.password": ["Password", "Parol", "Пароль"],
  "login.password_new": ["Password (at least 8 characters)", "Parol (ən azı 8 simvol)", "Пароль (не менее 8 символов)"],
  "login.btn_signin": ["Sign in", "Daxil ol", "Войти"],
  "login.btn_register": ["Create my account", "Hesabımı yarat", "Создать учётную запись"],
  "login.btn_setup": ["Create the admin account", "Admin hesabını yarat", "Создать запись админа"],
  "login.busy": ["One moment…", "Bir an…", "Секунду…"],
  "login.no_account": ["No account yet?", "Hesabınız yoxdur?", "Нет учётной записи?"],
  "login.admin_hint": [
    "The admin signs in here too, with the admin email and password.",
    "Admin də buradan, öz e-poçtu və parolu ilə daxil olur.",
    "Админ входит здесь же, со своей почтой и паролем.",
  ],
  "login.already": ["Already registered?", "Artıq qeydiyyatdan keçmisiniz?", "Уже зарегистрированы?"],
  "login.no_admin": ["FiscalAI has no admin account yet.", "FiscalAI-da hələ admin hesabı yoxdur.", "В FiscalAI пока нет записи админа."],
  "login.setup_link": ["Set up the admin", "Admini quraşdır", "Создать админа"],
  "login.failed": ["That didn't work. Try again.", "Alınmadı. Yenidən cəhd edin.", "Не получилось. Попробуйте ещё раз."],

  // ---------------------------------------------------------------- landing page
  "home.h1": [
    "Every invoice checked against policy before anyone pays it.",
    "Hər faktura ödənişdən əvvəl siyasətə görə yoxlanılır.",
    "Каждый счёт проверяется по политике до оплаты.",
  ],
  "home.lede": [
    "Employees send their invoice as a PDF. FiscalAI reads it, applies the expense policy, and alerts the audit team when a rule is broken, naming the rule and showing the numbers.",
    "İşçilər fakturanı PDF kimi göndərir. FiscalAI onu oxuyur, xərc siyasətini tətbiq edir və qayda pozulanda audit komandasına xəbər verir: hansı qayda və hansı rəqəmlərlə.",
    "Сотрудники отправляют счёт в PDF. FiscalAI читает его, применяет политику расходов и оповещает аудит, если правило нарушено: какое правило и с какими цифрами.",
  ],
  "home.cta_audit": ["Open the audit desk", "Audit masasını aç", "Открыть стол аудита"],
  "home.cta_register": ["Register", "Qeydiyyat", "Регистрация"],
  "home.how": ["What happens to a submitted invoice", "Göndərilən faktura ilə nə baş verir", "Что происходит с отправленным счётом"],
  "home.s1_t": ["The AI reads it", "AI onu oxuyur", "ИИ читает его"],
  "home.s1_p": [
    "Vendor, amount, dates, nights, guests and approvals are pulled from the PDF, a photo or an email, in English, Azerbaijani or Russian.",
    "Satıcı, məbləğ, tarixlər, gecələr, qonaqlar və təsdiqlər PDF-dən, şəkildən və ya e-poçtdan çıxarılır: ingilis, Azərbaycan və ya rus dilində.",
    "Поставщик, сумма, даты, ночи, гости и согласования извлекаются из PDF, фото или письма: на английском, азербайджанском или русском.",
  ],
  "home.s2_t": ["The policy decides", "Qərarı siyasət verir", "Решает политика"],
  "home.s2_p": [
    "Fixed rules do the maths: per person, per night, approval levels, approved vendors. Text hidden in the invoice can't change the outcome.",
    "Hesabı sabit qaydalar aparır: adambaşı, gecəbaşı, təsdiq səviyyələri, təsdiqlənmiş satıcılar. Fakturada gizlədilmiş mətn nəticəni dəyişə bilməz.",
    "Расчёт ведут жёсткие правила: на человека, за ночь, уровни согласования, утверждённые поставщики. Скрытый в счёте текст не изменит результат.",
  ],
  "home.s3_t": ["The audit team is alerted", "Audit komandasına xəbər gedir", "Аудит получает оповещение"],
  "home.s3_p": [
    "Clean invoices pass. Anything flagged or unclear lands on the audit desk with the reason, ready to approve or reject.",
    "Təmiz fakturalar keçir. Pozuntu və ya aydın olmayan hər şey səbəbi ilə birlikdə audit masasına düşür: təsdiq və ya rədd üçün hazır.",
    "Чистые счета проходят. Всё с нарушением или неясное попадает на стол аудита с причиной: одобрить или отклонить.",
  ],
  "home.rules": ["The rules being enforced", "Tətbiq olunan qaydalar", "Действующие правила"],

  "hero.aria": ["Example invoice from {vendor}", "{vendor} nümunə fakturası", "Пример счёта от {vendor}"],
  "hero.examples": ["Example invoices", "Nümunə fakturalar", "Примеры счетов"],
  "hero.invoice": ["Invoice {no}", "Faktura {no}", "Счёт {no}"],
  "hero.employee": ["Employee", "İşçi", "Сотрудник"],
  "hero.category": ["Category", "Kateqoriya", "Категория"],
  "hero.description": ["Description", "Təsvir", "Описание"],
  "hero.amount": ["Amount", "Məbləğ", "Сумма"],
  "hero.approval": ["Approval", "Təsdiq", "Согласование"],
  "hero.t1": ["Hotel, 3 nights", "Otel, 3 gecə", "Отель, 3 ночи"],
  "hero.t2": ["Client lunch", "Müştəri ilə nahar", "Обед с клиентом"],
  "hero.t3": ["Office monitor", "Ofis monitoru", "Офисный монитор"],
  "hero.c1": ["Travel - Accommodation", "Səfər - Yaşayış", "Поездки - Проживание"],
  "hero.c2": ["Meals & Entertainment", "Yemək və qonaqlıq", "Питание и представительские"],
  "hero.c3": ["Office Equipment", "Ofis avadanlığı", "Офисное оборудование"],
  "hero.d1": ["Executive room, 3 nights", "Lüks otaq, 3 gecə", "Номер «люкс», 3 ночи"],
  "hero.d2": ["Lunch with 2 clients", "2 müştəri ilə nahar", "Обед с 2 клиентами"],
  "hero.d3": ["Replacement monitor", "Əvəzedici monitor", "Монитор на замену"],
  "hero.a1": ["Manager Rauf Ismayilov", "Menecer Rauf İsmayılov", "Менеджер Рауф Исмаилов"],
  "hero.a2": ["Not needed under 500", "500-dən aşağı lazım deyil", "До 500 не требуется"],
  "hero.a3": ["None stated", "Göstərilməyib", "Не указано"],
  "hero.k1": [
    "1140 / 3 nights = 380 per night; limit 300",
    "1140 / 3 gecə = gecəsi 380; limit 300",
    "1140 / 3 ночи = 380 за ночь; лимит 300",
  ],
  "hero.k2": [
    "390 / 3 people = 130 per person; limit 150",
    "390 / 3 nəfər = adambaşı 130; limit 150",
    "390 / 3 человека = 130 на человека; лимит 150",
  ],
  "hero.k3": [
    "No policy rule covers office equipment; sent to a person",
    "Ofis avadanlığı üçün qayda yoxdur; insana göndərildi",
    "Для офисного оборудования правила нет; передано человеку",
  ],

  "policy.loading": ["Loading the policy…", "Siyasət yüklənir…", "Загружаем политику…"],
  "policy.error": [
    "The policy couldn't be loaded. Start the backend and refresh.",
    "Siyasət yüklənmədi. Backend-i işə salıb səhifəni yeniləyin.",
    "Не удалось загрузить политику. Запустите backend и обновите страницу.",
  ],
  "policy.intro": [
    "{company} expense policy {version}. Invoices are accepted in {list}.",
    "{company} xərc siyasəti {version}. Fakturalar {list} valyutalarında qəbul olunur.",
    "Политика расходов {company} {version}. Счета принимаются в {list}.",
  ],
  "policy.rates": [
    "Limits are in {cur}; other currencies are converted at {rates}.",
    "Limitlər {cur} ilədir; digər valyutalar bu məzənnə ilə çevrilir: {rates}.",
    "Лимиты указаны в {cur}; другие валюты пересчитываются по курсу: {rates}.",
  ],
  "policy.dup": [
    "An invoice that was already submitted is refused at upload, whoever sends it.",
    "Artıq göndərilmiş faktura yüklənərkən rədd edilir, kim göndərirsə göndərsin.",
    "Уже отправленный счёт отклоняется при загрузке, кто бы его ни отправил.",
  ],
  "rule.EXP-1.1": [
    "Client and team meal expenses may not exceed 150 AZN per person per day.",
    "Müştəri və komanda yeməyi xərcləri gündə adambaşı 150 AZN-i keçə bilməz.",
    "Расходы на питание с клиентами и командой не могут превышать 150 AZN на человека в день.",
  ],
  "rule.EXP-1.2": [
    "Hotel accommodation may not exceed 300 AZN per night without Director pre-approval.",
    "Otel xərci Direktorun əvvəlcədən təsdiqi olmadan gecəsi 300 AZN-i keçə bilməz.",
    "Проживание в отеле не может превышать 300 AZN за ночь без предварительного согласования директора.",
  ],
  "rule.EXP-2.1": [
    "Software and SaaS purchases over 1000 AZN require prior written approval from the IT department before purchase.",
    "1000 AZN-dən yuxarı proqram təminatı və SaaS alışları üçün alışdan əvvəl İT şöbəsinin yazılı təsdiqi tələb olunur.",
    "Покупки ПО и SaaS дороже 1000 AZN требуют предварительного письменного согласования ИТ-отдела.",
  ],
  "rule.EXP-3.1": [
    "All vendor payments must be made to vendors on the Approved Vendor List. Payments to unlisted vendors require Finance Director sign-off documented on the invoice.",
    "Bütün ödənişlər Təsdiqlənmiş Satıcılar Siyahısındakı satıcılara edilməlidir. Siyahıda olmayan satıcıya ödəniş üçün fakturada Maliyyə Direktorunun imzası olmalıdır.",
    "Все платежи должны идти поставщикам из Списка утверждённых поставщиков. Для поставщика вне списка нужна подпись финансового директора на счёте.",
  ],
  "rule.EXP-4.1": [
    "Any single expense between 500 and 2000 AZN requires Manager approval. Expenses above 2000 AZN require Finance Director approval. The approval must be stated on the invoice/expense record.",
    "500 ilə 2000 AZN arasındakı hər xərc üçün Menecer təsdiqi tələb olunur. 2000 AZN-dən yuxarı xərclər üçün Maliyyə Direktorunun təsdiqi lazımdır. Təsdiq fakturada göstərilməlidir.",
    "Любой расход от 500 до 2000 AZN требует согласования менеджера. Расходы свыше 2000 AZN требуют согласования финансового директора. Согласование должно быть указано в счёте.",
  ],

  // ---------------------------------------------------------------- submit
  "submit.lede": [
    "Send the invoice for an expense you paid or want paid. It is checked against the expense policy in a few seconds, and anything that needs a closer look goes to the audit team.",
    "Ödədiyiniz və ya ödənilməsini istədiyiniz xərcin fakturasını göndərin. O, bir neçə saniyəyə xərc siyasətinə görə yoxlanılır; diqqət tələb edən hər şey audit komandasına gedir.",
    "Отправьте счёт за расход, который вы оплатили или хотите оплатить. За несколько секунд он проверяется по политике расходов; всё, что требует внимания, уходит аудиту.",
  ],
  "submit.drop": ["Drop your invoice PDF here", "Faktura PDF-ini bura atın", "Перетащите PDF счёта сюда"],
  "submit.drop_hint": [
    "or click to choose a file. PDF, PNG, JPEG or WEBP up to 5 MB.",
    "və ya fayl seçmək üçün klikləyin. PDF, PNG, JPEG və ya WEBP, 5 MB-a qədər.",
    "или нажмите, чтобы выбрать файл. PDF, PNG, JPEG или WEBP до 5 МБ.",
  ],
  "submit.replace": [
    "{kb} KB. Choose a different file or drop one here to replace it.",
    "{kb} KB. Dəyişmək üçün başqa fayl seçin və ya bura atın.",
    "{kb} КБ. Чтобы заменить, выберите или перетащите другой файл.",
  ],
  "submit.samples": ["No invoice to hand? Try one of these:", "Əlinizdə faktura yoxdur? Bunlardan birini sınayın:", "Нет счёта под рукой? Попробуйте один из этих:"],
  "sample.1-team-lunch-approved.pdf": ["Team lunch, approved", "Komanda naharı, təsdiqli", "Обед команды, согласован"],
  "sample.2-hotel-over-limit.pdf": ["Hotel over limit", "Otel limitdən yuxarı", "Отель сверх лимита"],
  "sample.3-unlisted-software-vendor.pdf": ["Unlisted software vendor", "Siyahıda olmayan proqram satıcısı", "Поставщик ПО вне списка"],
  "sample.4-forged-approval-note.pdf": ["Forged approval note", "Saxta təsdiq qeydi", "Поддельная отметка о согласовании"],
  "sample.5-scanned-receipt-needs-ai.pdf": ["Scanned receipt (needs AI)", "Skan edilmiş qəbz (AI lazımdır)", "Скан чека (нужен ИИ)"],
  "sample.6-hotel-in-euro.pdf": ["Hotel in euro", "Otel, avro ilə", "Отель в евро"],
  "sample.7-software-in-dollars.pdf": ["Software in dollars", "Proqram təminatı, dollarla", "ПО в долларах"],
  "submit.by": ["Submitted by", "Göndərən", "Отправитель"],
  "submit.currency": ["Invoice currency", "Faktura valyutası", "Валюта счёта"],
  "submit.currency_auto": ["As printed on the invoice", "Fakturada yazıldığı kimi", "Как указано в счёте"],
  "submit.accepts": ["FiscalAI accepts {list}.", "FiscalAI {list} qəbul edir.", "FiscalAI принимает {list}."],
  "submit.rates": [
    "Limits are in {cur}, so other currencies are converted at the fixed policy rates: {rates}.",
    "Limitlər {cur} ilədir, ona görə digər valyutalar sabit məzənnə ilə çevrilir: {rates}.",
    "Лимиты указаны в {cur}, поэтому другие валюты пересчитываются по фиксированному курсу: {rates}.",
  ],
  "submit.currency_only": [
    "Choose a currency only if the invoice doesn't show one.",
    "Valyutanı yalnız fakturada göstərilməyibsə seçin.",
    "Выбирайте валюту, только если в счёте она не указана.",
  ],
  "submit.note": ["Note for the audit team (optional)", "Audit komandası üçün qeyd (istəyə görə)", "Примечание для аудита (необязательно)"],
  "submit.note_ph": [
    "For example: client visit to Ganja, booked by the travel agency.",
    "Məsələn: Gəncəyə müştəri səfəri, səyahət agentliyi sifariş edib.",
    "Например: визит к клиенту в Гянджу, бронировало турагентство.",
  ],
  "submit.send": ["Send invoice", "Fakturanı göndər", "Отправить счёт"],
  "submit.sending": ["Checking your invoice…", "Fakturanız yoxlanılır…", "Проверяем ваш счёт…"],
  "submit.empty": [
    "Your result will appear here once you send the invoice.",
    "Fakturanı göndərən kimi nəticə burada görünəcək.",
    "Результат появится здесь, как только вы отправите счёт.",
  ],
  "submit.x_ok": ["Passed to Finance for payment", "Ödəniş üçün Maliyyəyə ötürüldü", "Передан в финансы на оплату"],
  "submit.x_flag": ["A rule is broken; the audit team is alerted", "Qayda pozulub; audit komandasına xəbər verildi", "Нарушено правило; аудит оповещён"],
  "submit.x_review": ["A person needs to check something", "İnsan nəyisə yoxlamalıdır", "Человек должен кое-что проверить"],
  "submit.follow": ["Follow everything you have sent on", "Göndərdiyiniz hər şeyi burada izləyin:", "Следите за всем отправленным на странице"],
  "submit.scan": [
    "Reading {file} and checking it against 5 policy rules…",
    "{file} oxunur və 5 siyasət qaydasına görə yoxlanılır…",
    "Читаем {file} и проверяем по 5 правилам политики…",
  ],
  "submit.dup": [
    "This invoice is already in FiscalAI, so it was not submitted again.",
    "Bu faktura artıq FiscalAI-dadır, ona görə yenidən göndərilmədi.",
    "Этот счёт уже есть в FiscalAI, поэтому повторно он не отправлен.",
  ],
  "submit.see_my": ["See my invoices", "Fakturalarıma bax", "Мои счета"],
  "submit.different": ["Submit a different invoice", "Başqa faktura göndər", "Отправить другой счёт"],
  "submit.ref": ["Submission #{id}", "Göndəriş #{id}", "Отправка №{id}"],
  "submit.msg_ok": [
    "Your invoice follows the expense policy. It has been passed to Finance for payment.",
    "Fakturanız xərc siyasətinə uyğundur. Ödəniş üçün Maliyyəyə ötürüldü.",
    "Ваш счёт соответствует политике расходов. Он передан в финансы на оплату.",
  ],
  "submit.msg_flagged": [
    "Your invoice breaks one or more expense-policy rules. It has been sent to the audit team, who may contact you. The reasons are listed below.",
    "Fakturanız xərc siyasətinin bir və ya bir neçə qaydasını pozur. O, audit komandasına göndərildi; sizinlə əlaqə saxlaya bilərlər. Səbəblər aşağıdadır.",
    "Ваш счёт нарушает одно или несколько правил политики расходов. Он отправлен аудиту; с вами могут связаться. Причины указаны ниже.",
  ],
  "submit.msg_review": [
    "Your invoice needs a person to check it before it can be paid. It has been sent to the audit team.",
    "Fakturanız ödənilməzdən əvvəl insan tərəfindən yoxlanmalıdır. O, audit komandasına göndərildi.",
    "Перед оплатой ваш счёт должен проверить человек. Он отправлен аудиту.",
  ],
  "submit.fx": [
    "Converted at the fixed policy rate: 1 {from} = {rate} {to}.",
    "Sabit siyasət məzənnəsi ilə çevrildi: 1 {from} = {rate} {to}.",
    "Пересчитано по фиксированному курсу политики: 1 {from} = {rate} {to}.",
  ],
  "submit.breaks": ["What breaks the policy", "Siyasəti nə pozur", "Что нарушает политику"],
  "submit.why": ["Why a person will look at it", "Niyə insan baxacaq", "Почему посмотрит человек"],
  "submit.another": ["Submit another invoice", "Daha bir faktura göndər", "Отправить ещё счёт"],
  "submit.e_type": [
    "{name} isn't a PDF or an image. Export the invoice as PDF and try again.",
    "{name} PDF və ya şəkil deyil. Fakturanı PDF kimi ixrac edib yenidən cəhd edin.",
    "{name} не PDF и не изображение. Экспортируйте счёт в PDF и попробуйте снова.",
  ],
  "submit.e_size": ["{name} is {mb} MB. The limit is 5 MB.", "{name} {mb} MB-dır. Limit 5 MB-dır.", "{name} весит {mb} МБ. Лимит 5 МБ."],
  "submit.e_sample": [
    "The sample couldn't be loaded. Check that the backend is running.",
    "Nümunə yüklənmədi. Backend-in işlədiyini yoxlayın.",
    "Не удалось загрузить пример. Проверьте, что backend запущен.",
  ],
  "submit.e_nofile": ["Add your invoice PDF first.", "Əvvəlcə faktura PDF-ini əlavə edin.", "Сначала добавьте PDF счёта."],
  "submit.e_send": ["The invoice couldn't be sent.", "Faktura göndərilmədi.", "Не удалось отправить счёт."],

  "f.vendor": ["Vendor", "Satıcı", "Поставщик"],
  "f.amount": ["Amount", "Məbləğ", "Сумма"],
  "f.category": ["Category", "Kateqoriya", "Категория"],
  "f.date": ["Date", "Tarix", "Дата"],
  "f.invoice_no": ["Invoice number", "Faktura nömrəsi", "Номер счёта"],
  "f.employee_on": ["Employee on invoice", "Fakturadakı işçi", "Сотрудник в счёте"],
  "f.approval_needed": ["Approval needed", "Tələb olunan təsdiq", "Требуемое согласование"],

  // ---------------------------------------------------------------- my invoices
  "my.lede": [
    "Everything you have submitted and where each invoice stands.",
    "Göndərdiyiniz hər şey və hər fakturanın vəziyyəti.",
    "Всё, что вы отправили, и статус каждого счёта.",
  ],
  "my.empty": [
    "You haven't submitted an invoice yet. Once you do, its result and the audit team's decision show up here.",
    "Hələ faktura göndərməmisiniz. Göndərəndən sonra nəticə və audit komandasının qərarı burada görünəcək.",
    "Вы ещё не отправляли счетов. После отправки здесь появятся результат и решение аудита.",
  ],
  "my.in_review": ["With the audit team", "Audit komandasındadır", "У аудита"],
  "my.cleared": ["Cleared to pay", "Ödənişə buraxıldı", "Допущен к оплате"],
  "my.rejected": ["Rejected", "Rədd edildi", "Отклонён"],
  "my.m_in_review": ["An auditor is looking at it.", "Auditor ona baxır.", "Его рассматривает аудитор."],
  "my.m_cleared": ["Passed to Finance for payment.", "Ödəniş üçün Maliyyəyə ötürüldü.", "Передан в финансы на оплату."],
  "my.m_rejected": [
    "Fix what the auditor asked for and send it again.",
    "Auditorun istədiyini düzəldib yenidən göndərin.",
    "Исправьте то, о чём просил аудитор, и отправьте снова.",
  ],
  "my.sent": ["#{id}, sent {date}", "#{id}, göndərilib: {date}", "№{id}, отправлен {date}"],
  "my.invoice": ["invoice {no}", "faktura {no}", "счёт {no}"],
  "my.decided": ["Decided by {who} on {when}", "Qərar: {who}, {when}", "Решение: {who}, {when}"],
  "my.open_file": ["Open the file you sent ({file})", "Göndərdiyiniz faylı aç ({file})", "Открыть отправленный файл ({file})"],
  "my.error": ["Your invoices couldn't be loaded.", "Fakturalarınız yüklənmədi.", "Не удалось загрузить ваши счета."],

  // ---------------------------------------------------------------- audit desk
  "audit.live": [
    "New submissions appear here automatically.",
    "Yeni göndərişlər burada avtomatik görünür.",
    "Новые отправки появляются здесь автоматически.",
  ],
  "audit.alerts_on": ["Turn on desktop alerts", "Masaüstü bildirişləri yandır", "Включить уведомления"],
  "audit.filters": ["Filter invoices", "Fakturaları süz", "Фильтр счетов"],
  "audit.f_open": ["Open alerts", "Açıq xəbərdarlıqlar", "Открытые оповещения"],
  "audit.f_decided": ["Decided", "Qərar verilib", "Решённые"],
  "audit.f_all": ["All invoices", "Bütün fakturalar", "Все счета"],
  "audit.invoices": ["Invoices", "Fakturalar", "Счета"],
  "audit.empty_open": [
    "No open alerts. Flagged invoices and anything that needs a person will appear here.",
    "Açıq xəbərdarlıq yoxdur. Pozuntulu və insan yoxlaması tələb edən fakturalar burada görünəcək.",
    "Открытых оповещений нет. Счета с нарушениями и всё, что требует человека, появятся здесь.",
  ],
  "audit.empty": ["No invoices in this view yet.", "Bu görünüşdə hələ faktura yoxdur.", "В этом представлении пока нет счетов."],
  "audit.new": ["New", "Yeni", "Новый"],
  "audit.cleared": ["Cleared", "Buraxıldı", "Допущен"],
  "audit.warnings": ["Warnings: {n}", "Xəbərdarlıq: {n}", "Предупреждений: {n}"],
  "audit.select": [
    "Select an invoice to see why it was flagged, the original document and the decision buttons.",
    "Fakturanı seçin: niyə işarələndiyini, orijinal sənədi və qərar düymələrini görəcəksiniz.",
    "Выберите счёт, чтобы увидеть причину, исходный документ и кнопки решения.",
  ],
  "audit.toast": ["{status}: invoice from {name}", "{status}: {name} faktura göndərdi", "{status}: счёт от {name}"],
  "audit.tab": ["Audit desk — FiscalAI", "Audit masası — FiscalAI", "Стол аудита — FiscalAI"],
  "audit.n_on": ["Desktop alerts turned on", "Masaüstü bildirişlər yandırıldı", "Уведомления включены"],
  "audit.n_on_b": [
    "You'll be notified even when this tab is in the background.",
    "Bu vərəq arxa planda olanda da bildiriş alacaqsınız.",
    "Вы получите уведомление, даже если вкладка в фоне.",
  ],
  "audit.n_off": ["Desktop alerts are blocked", "Masaüstü bildirişlər bloklanıb", "Уведомления заблокированы"],
  "audit.n_off_b": [
    "Allow notifications for this site in your browser settings.",
    "Brauzer ayarlarında bu sayt üçün bildirişlərə icazə verin.",
    "Разрешите уведомления для этого сайта в настройках браузера.",
  ],
  "audit.n_none": [
    "This browser doesn't support desktop alerts",
    "Bu brauzer masaüstü bildirişləri dəstəkləmir",
    "Этот браузер не поддерживает уведомления",
  ],
  "audit.ref": ["Submission #{id}, {when}", "Göndəriş #{id}, {when}", "Отправка №{id}, {when}"],
  "audit.sent_by": ["Sent by {name}", "Göndərən: {name}", "Отправил: {name}"],
  "audit.original": ["Original document", "Orijinal sənəd", "Исходный документ"],
  "audit.new_tab": ["Open in a new tab", "Yeni vərəqdə aç", "Открыть в новой вкладке"],
  "audit.doc": ["Invoice {file}", "Faktura {file}", "Счёт {file}"],
  "audit.decision": ["Decision", "Qərar", "Решение"],
  "audit.your_decision": ["Your decision", "Sizin qərarınız", "Ваше решение"],
  "audit.decided": ["{what}: {who}, {when}.", "{what}: {who}, {when}.", "{what}: {who}, {when}."],
  "audit.own": [
    "You submitted this invoice yourself, so another auditor has to decide on it.",
    "Bu fakturanı özünüz göndərmisiniz, ona görə qərarı başqa auditor verməlidir.",
    "Вы сами отправили этот счёт, поэтому решение должен принять другой аудитор.",
  ],
  "audit.comment": [
    "Comment to the employee (needed to reject)",
    "İşçiyə şərh (rədd etmək üçün vacibdir)",
    "Комментарий сотруднику (обязателен при отклонении)",
  ],
  "audit.recorded": [
    "The decision is recorded under your name, {name}.",
    "Qərar sizin adınıza yazılır: {name}.",
    "Решение записывается на ваше имя: {name}.",
  ],
  "audit.clear": ["Clear to pay", "Ödənişə burax", "Допустить к оплате"],
  "audit.clearing": ["Clearing…", "Buraxılır…", "Допускаем…"],
  "audit.reject": ["Reject", "Rədd et", "Отклонить"],
  "audit.rejecting": ["Rejecting…", "Rədd edilir…", "Отклоняем…"],
  "audit.t_cleared": ["Invoice #{id} cleared to pay", "Faktura #{id} ödənişə buraxıldı", "Счёт №{id} допущен к оплате"],
  "audit.t_rejected": ["Invoice #{id} rejected", "Faktura #{id} rədd edildi", "Счёт №{id} отклонён"],
  "audit.e_save": ["The decision couldn't be saved.", "Qərar yadda saxlanmadı.", "Не удалось сохранить решение."],

  "result.broken": ["Rules broken", "Pozulan qaydalar", "Нарушенные правила"],
  "result.severity": ["{sev} severity", "ciddilik: {sev}", "серьёзность: {sev}"],
  "sev.low": ["low", "aşağı", "низкая"],
  "sev.medium": ["medium", "orta", "средняя"],
  "sev.high": ["high", "yüksək", "высокая"],
  "result.policy": ["Policy: {text}", "Siyasət: {text}", "Политика: {text}"],
  "result.person": ["Needs a person because", "İnsan yoxlaması lazımdır, çünki", "Нужен человек, потому что"],
  "result.clean": [
    "Every rule that applies to this invoice passed.",
    "Bu fakturaya aid bütün qaydalar keçdi.",
    "Все применимые к этому счёту правила пройдены.",
  ],
  "result.how": ["How each rule was checked", "Hər qayda necə yoxlanıldı", "Как проверялось каждое правило"],
  "res.pass": ["pass", "keçdi", "пройдено"],
  "res.violation": ["violation", "pozuntu", "нарушение"],
  "res.skipped": ["skipped", "ötürüldü", "пропущено"],
  "res.info": ["info", "məlumat", "инфо"],
  "result.meta_offline": [
    "Fields read by the offline reader; verdict decided by the policy rules.",
    "Sahələri oflayn oxuyucu oxuyub; hökmü siyasət qaydaları verib.",
    "Поля прочитаны офлайн-модулем; вердикт вынесен правилами политики.",
  ],
  "result.meta_model": [
    "Fields read by the {provider} model; verdict decided by the policy rules.",
    "Sahələri {provider} modeli oxuyub; hökmü siyasət qaydaları verib.",
    "Поля прочитаны моделью {provider}; вердикт вынесен правилами политики.",
  ],
  "result.took": ["Took {ms} ms.", "{ms} ms çəkdi.", "Заняло {ms} мс."],
  "result.not_logged": [
    "Warning: not written to the audit log.",
    "Xəbərdarlıq: audit jurnalına yazılmadı.",
    "Внимание: не записано в журнал аудита.",
  ],

  // ---------------------------------------------------------------- overview
  "ov.live": [
    "Every invoice submitted so far. Updates on its own.",
    "İndiyə qədər göndərilən bütün fakturalar. Özü yenilənir.",
    "Все отправленные на данный момент счета. Обновляется само.",
  ],
  "ov.csv": ["Download all invoices (CSV)", "Bütün fakturaları yüklə (CSV)", "Скачать все счета (CSV)"],
  "ov.loading": ["Loading the overview…", "Hesabat yüklənir…", "Загружаем отчёт…"],
  "ov.error": ["The overview couldn't be loaded.", "Hesabat yüklənmədi.", "Не удалось загрузить отчёт."],
  "ov.t_submitted": ["Invoices submitted", "Göndərilən fakturalar", "Отправлено счетов"],
  "ov.t_waiting": ["Waiting for an auditor", "Auditor gözləyir", "Ждут аудитора"],
  "ov.t_cleared": ["Cleared to pay", "Ödənişə buraxıldı", "Допущено к оплате"],
  "ov.t_cleared_sub": ["{money}, {n} without an auditor", "{money}, {n} auditorsuz", "{money}, без аудитора: {n}"],
  "ov.t_rejected": ["Rejected", "Rədd edildi", "Отклонено"],
  "ov.t_dups": ["Duplicates refused", "Rədd edilən dublikatlar", "Отклонено дубликатов"],
  "ov.t_dups_sub": ["never entered the queue", "növbəyə düşmədi", "в очередь не попали"],
  "ov.t_time": ["Time to a decision", "Qərara qədər vaxt", "Время до решения"],
  "ov.t_time_sub": ["average over {n} decisions", "{n} qərar üzrə orta", "в среднем по решениям: {n}"],
  "ov.totals": ["Totals are in {cur}.", "Cəmlər {cur} ilədir.", "Итоги в {cur}."],
  "ov.rates": ["Fixed policy rates: {rates}.", "Sabit siyasət məzənnələri: {rates}.", "Фиксированные курсы политики: {rates}."],
  "ov.unconverted": [
    "Invoices in a currency without a rate, not counted in the totals: {n}.",
    "Məzənnəsi olmayan valyutada, cəmə daxil edilməyən fakturalar: {n}.",
    "Счета в валюте без курса, не вошедшие в итоги: {n}.",
  ],
  "ov.daily": ["Invoices per day, last {n} days", "Günlük fakturalar, son {n} gün", "Счета по дням, последние {n} дней"],
  "ov.as_table": ["Show as table", "Cədvəl kimi göstər", "Показать таблицей"],
  "ov.as_chart": ["Show as chart", "Qrafik kimi göstər", "Показать графиком"],
  "ov.legend": ["Verdict given by the policy check", "Siyasət yoxlamasının hökmü", "Вердикт проверки по политике"],
  "ov.day": ["Day", "Gün", "День"],
  "ov.total": ["Total", "Cəmi", "Всего"],
  "ov.no_period": [
    "No invoices were submitted in this period.",
    "Bu dövrdə faktura göndərilməyib.",
    "За этот период счета не отправлялись.",
  ],
  "ov.rules": ["Rules broken most often", "Ən çox pozulan qaydalar", "Чаще всего нарушаемые правила"],
  "ov.no_rules": ["No rule has been broken yet.", "Hələ heç bir qayda pozulmayıb.", "Пока ни одно правило не нарушено."],
  "ov.by_currency": ["By currency", "Valyuta üzrə", "По валютам"],
  "ov.no_amounts": ["No readable amounts yet.", "Hələ oxunan məbləğ yoxdur.", "Пока нет прочитанных сумм."],
  "ov.c_currency": ["Currency", "Valyuta", "Валюта"],
  "ov.c_invoices": ["Invoices", "Fakturalar", "Счета"],
  "ov.c_as_invoiced": ["As invoiced", "Fakturadakı kimi", "Как в счёте"],
  "ov.c_in": ["In {cur}", "{cur} ilə", "В {cur}"],
  "ov.no_rate": ["no rate", "məzənnə yoxdur", "нет курса"],
  "ov.by_employee": ["By employee", "İşçi üzrə", "По сотрудникам"],
  "ov.no_employee": ["Nobody has submitted an invoice yet.", "Hələ heç kim faktura göndərməyib.", "Пока никто не отправлял счетов."],
  "ov.c_total_in": ["Total in {cur}", "Cəmi, {cur}", "Итого, {cur}"],
  "ov.decisions": ["Latest decisions", "Son qərarlar", "Последние решения"],
  "ov.no_decisions": [
    "No auditor has decided on an invoice yet.",
    "Hələ heç bir auditor qərar verməyib.",
    "Пока ни один аудитор не принял решения.",
  ],
  "ov.from_by": ["from {emp}. By", "göndərən: {emp}. Qərar:", "от {emp}. Решил(а):"],
  "ov.per_auditor": ["Decisions per auditor: {list}.", "Auditor üzrə qərarlar: {list}.", "Решений по аудиторам: {list}."],
  "ov.dups": ["Duplicates refused", "Rədd edilən dublikatlar", "Отклонённые дубликаты"],
  "ov.no_dups": [
    "Nobody has tried to submit the same invoice twice.",
    "Heç kim eyni fakturanı iki dəfə göndərməyə çalışmayıb.",
    "Никто не пытался отправить один счёт дважды.",
  ],
  "ov.dup_sent": ["sent", "göndərdi:", "отправил(а)"],
  "ov.dup_file": ["the same file as", "eyni fayl, bax:", "тот же файл, что и"],
  "ov.dup_number": ["the same vendor and invoice number as", "eyni satıcı və faktura nömrəsi, bax:", "тот же поставщик и номер счёта, что и"],
  "ov.dup_amount": ["the same vendor, amount and date as", "eyni satıcı, məbləğ və tarix, bax:", "тот же поставщик, сумма и дата, что и"],
  "ov.submission": ["submission #{id}", "göndəriş #{id}", "отправка №{id}"],
  "unit.min": ["{n} min", "{n} dəq", "{n} мин"],
  "unit.h": ["{n} h", "{n} saat", "{n} ч"],
  "unit.days": ["{n} days", "{n} gün", "{n} дн."],

  // ---------------------------------------------------------------- accounts
  "users.lede": [
    "Everyone who registered, and what each person can do. People create their own account as an employee or an auditor; you can correct a role, set a new password or end someone's access.",
    "Qeydiyyatdan keçən hər kəs və hər birinin səlahiyyəti. İnsanlar hesabını işçi və ya auditor kimi özləri yaradır; siz rolu düzəldə, yeni parol qoya və ya girişi bağlaya bilərsiniz.",
    "Все зарегистрированные и права каждого. Люди сами создают запись сотрудника или аудитора; вы можете исправить роль, задать новый пароль или закрыть доступ.",
  ],
  "users.waiting": ["Waiting for your approval ({n})", "Təsdiqinizi gözləyənlər ({n})", "Ожидают вашего подтверждения ({n})"],
  "users.waiting_p": [
    "These people registered as auditors. An auditor sees every invoice and can clear it for payment, so approve only people who should have that.",
    "Bu şəxslər auditor kimi qeydiyyatdan keçib. Auditor bütün fakturaları görür və ödənişə buraxa bilir, ona görə yalnız uyğun şəxsləri təsdiqləyin.",
    "Эти люди зарегистрировались как аудиторы. Аудитор видит все счета и может допустить их к оплате, поэтому подтверждайте только тех, кому это положено.",
  ],
  "users.registered": ["registered {ago}", "qeydiyyat: {ago}", "регистрация: {ago}"],
  "users.approve": ["Approve as auditor", "Auditor kimi təsdiqlə", "Подтвердить аудитором"],
  "users.decline": ["Decline", "Rədd et", "Отклонить"],
  "users.t_approved": ["{name} is now an auditor", "{name} artıq auditordur", "{name} теперь аудитор"],
  "users.t_declined": ["{name} stays an employee", "{name} işçi olaraq qalır", "{name} остаётся сотрудником"],
  "users.people": ["People ({n} active)", "İstifadəçilər ({n} aktiv)", "Пользователи (активных: {n})"],
  "users.c_name": ["Name", "Ad", "Имя"],
  "users.c_role": ["Role", "Rol", "Роль"],
  "users.c_last": ["Last sign-in", "Son giriş", "Последний вход"],
  "users.actions": ["Actions", "Əməliyyatlar", "Действия"],
  "users.you": ["(you)", "(siz)", "(вы)"],
  "users.role_of": ["Role of {name}", "{name} üçün rol", "Роль: {name}"],
  "users.deactivated": ["Deactivated", "Deaktiv edilib", "Отключён"],
  "users.never": ["Never", "Heç vaxt", "Никогда"],
  "users.new_pw": ["New password", "Yeni parol", "Новый пароль"],
  "users.set": ["Set", "Təyin et", "Задать"],
  "users.set_pw": ["Set password", "Parol təyin et", "Задать пароль"],
  "users.deactivate": ["Deactivate", "Deaktiv et", "Отключить"],
  "users.reactivate": ["Reactivate", "Aktiv et", "Включить"],
  "users.t_role": ["{name}: role is now {role}", "{name}: rol indi {role}", "{name}: роль теперь {role}"],
  "users.t_pw": ["New password set for {name}", "{name} üçün yeni parol təyin edildi", "Для {name} задан новый пароль"],
  "users.t_off": ["{name} can no longer sign in", "{name} artıq daxil ola bilməz", "{name} больше не может войти"],
  "users.t_on": ["{name} can sign in again", "{name} yenidən daxil ola bilər", "{name} снова может войти"],
  "users.hint": [
    "Deactivating keeps the person's invoices and decisions in the record but ends their access at once. Setting a new password signs them out of every device; a new role applies at once.",
    "Deaktiv etmə şəxsin faktura və qərarlarını qeydlərdə saxlayır, amma girişini dərhal bağlayır. Yeni parol onu bütün cihazlardan çıxarır; yeni rol dərhal qüvvəyə minir.",
    "Отключение сохраняет счета и решения человека в записях, но сразу закрывает доступ. Новый пароль завершает сеансы на всех устройствах; новая роль действует сразу.",
  ],
  "users.add": ["Add a person", "İstifadəçi əlavə et", "Добавить пользователя"],
  "users.first_pw": ["First password (at least 8 characters)", "İlk parol (ən azı 8 simvol)", "Первый пароль (не менее 8 символов)"],
  "users.h_employee": ["submits invoices and follows their own", "faktura göndərir və öz fakturalarını izləyir", "отправляет счета и следит за своими"],
  "users.h_auditor": [
    "also clears or rejects invoices and sees the overview",
    "üstəlik fakturaları təsdiqləyir və ya rədd edir, hesabatı görür",
    "ещё одобряет или отклоняет счета и видит отчёт",
  ],
  "users.create": ["Create account", "Hesab yarat", "Создать запись"],
  "users.creating": ["Creating…", "Yaradılır…", "Создаём…"],
  "users.t_created": ["Account created for {name}", "{name} üçün hesab yaradıldı", "Запись для {name} создана"],
  "users.t_created_b": [
    "Give them the password you set. They sign in with {email}.",
    "Təyin etdiyiniz parolu ona verin. Giriş e-poçtu: {email}.",
    "Передайте заданный пароль. Вход по адресу {email}.",
  ],
  "users.change_hint": [
    "They can change the password themselves under their name in the top bar.",
    "Parolu özü yuxarı paneldəki adına klikləyib dəyişə bilər.",
    "Пароль можно сменить самостоятельно, нажав на своё имя в верхней панели.",
  ],
  "users.loading": ["Loading accounts…", "Hesablar yüklənir…", "Загружаем записи…"],
  "users.e_load": ["Accounts couldn't be loaded.", "Hesablar yüklənmədi.", "Не удалось загрузить записи."],
  "users.e_save": ["The change couldn't be saved.", "Dəyişiklik yadda saxlanmadı.", "Не удалось сохранить изменение."],
  "users.e_create": ["The account couldn't be created.", "Hesab yaradılmadı.", "Не удалось создать запись."],

  // ---------------------------------------------------------------- own account
  "acc.change": ["Change your password", "Parolunuzu dəyişin", "Смена пароля"],
  "acc.current": ["Current password", "Cari parol", "Текущий пароль"],
  "acc.btn": ["Change password", "Parolu dəyiş", "Сменить пароль"],
  "acc.saving": ["Saving…", "Yadda saxlanılır…", "Сохраняем…"],
  "acc.done": ["Password changed", "Parol dəyişdirildi", "Пароль изменён"],
  "acc.done_b": [
    "Other devices signed in to your account were signed out.",
    "Hesabınıza daxil olmuş digər cihazlardan çıxış edildi.",
    "Сеансы на других устройствах завершены.",
  ],
  "acc.error": ["The password couldn't be changed.", "Parol dəyişdirilmədi.", "Не удалось сменить пароль."],

  // ---------------------------------------------------------------- quick check
  "check.lede": [
    "Paste an invoice or expense record to see how the policy treats it. Nothing is sent to the audit team from here; to submit a real invoice, use",
    "Siyasətin necə tətbiq olunduğunu görmək üçün faktura və ya xərc qeydini yapışdırın. Buradan audit komandasına heç nə göndərilmir; real faktura üçün bu səhifədən istifadə edin:",
    "Вставьте счёт или запись о расходе, чтобы увидеть, как к нему применяется политика. Отсюда аудиту ничего не отправляется; для настоящего счёта используйте",
  ],
  "check.cases": ["Test cases", "Test nümunələri", "Тестовые примеры"],
  "check.text": ["Invoice text", "Faktura mətni", "Текст счёта"],
  "check.btn": ["Check against policy", "Siyasətə görə yoxla", "Проверить по политике"],
  "check.busy": ["Checking…", "Yoxlanılır…", "Проверяем…"],
  "check.empty": [
    "Pick a test case or paste an invoice, then check it.",
    "Test nümunəsi seçin və ya faktura yapışdırın, sonra yoxlayın.",
    "Выберите пример или вставьте счёт, затем проверьте.",
  ],
  "check.error": ["The check failed.", "Yoxlama alınmadı.", "Проверка не удалась."],
  // ---------------------------------------------------------------- theme
  "theme.light": ["Light", "Açıq", "Светлая"],
  "theme.dark": ["Dark", "Tünd", "Тёмная"],
  "theme.to_dark": ["Switch to the dark theme", "Tünd temaya keç", "Включить тёмную тему"],
  "theme.to_light": ["Switch to the light theme", "Açıq temaya keç", "Включить светлую тему"],

  // ---------------------------------------------------------------- audit tools
  "nav.employees": ["Employees", "İşçilər", "Сотрудники"],
  "audit.search": ["Search", "Axtarış", "Поиск"],
  "audit.search_ph": [
    "Employee, vendor, invoice number or #id",
    "İşçi, satıcı, faktura nömrəsi və ya #id",
    "Сотрудник, поставщик, номер счёта или #id",
  ],
  "audit.no_match": ["Nothing matches “{q}”.", "“{q}” üzrə heç nə tapılmadı.", "По запросу «{q}» ничего не найдено."],
  "audit.history": ["History", "Tarixçə", "История"],
  "ev.submitted": ["submitted the invoice", "fakturanı göndərdi", "отправил(а) счёт"],
  "ev.approved": ["cleared it to pay", "ödənişə buraxdı", "допустил(а) к оплате"],
  "ev.rejected": ["rejected it", "rədd etdi", "отклонил(а)"],
  "ev.reopened": ["reopened the decision", "qərarı yenidən açdı", "вернул(а) на рассмотрение"],
  "ev.note": ["added an internal note", "daxili qeyd əlavə etdi", "добавил(а) внутреннюю заметку"],
  "audit.note": [
    "Internal note (only the audit team sees it)",
    "Daxili qeyd (yalnız audit komandası görür)",
    "Внутренняя заметка (видит только аудит)",
  ],
  "audit.note_add": ["Add note", "Qeyd əlavə et", "Добавить заметку"],
  "audit.t_note": ["Note added", "Qeyd əlavə edildi", "Заметка добавлена"],
  "audit.reopen": ["Reopen the decision", "Qərarı yenidən aç", "Вернуть на рассмотрение"],
  "audit.reopen_why": [
    "Why is the decision being reopened? (kept in the history)",
    "Qərar niyə yenidən açılır? (tarixçədə saxlanılır)",
    "Почему решение пересматривается? (сохранится в истории)",
  ],
  "audit.reopen_do": ["Reopen", "Yenidən aç", "Вернуть"],
  "audit.t_reopened": ["Invoice #{id} is open again", "Faktura #{id} yenidən açıqdır", "Счёт №{id} снова открыт"],
  "audit.person": ["This employee's report", "Bu işçinin hesabatı", "Отчёт по этому сотруднику"],

  // ---------------------------------------------------------------- spending reports
  "rep.mine": ["My spending", "Xərclərim", "Мои расходы"],
  "rep.total": ["Submitted", "Göndərilib", "Отправлено"],
  "rep.cleared": ["Cleared to pay", "Ödənişə buraxılıb", "Допущено к оплате"],
  "rep.waiting": ["With the audit team", "Audit komandasındadır", "У аудита"],
  "rep.rejected": ["Rejected", "Rədd edilib", "Отклонено"],
  "rep.invoices": ["Invoices: {n}", "Faktura sayı: {n}", "Счетов: {n}"],
  "rep.monthly": ["Spending per month, {cur}", "Aylıq xərc, {cur}", "Расходы по месяцам, {cur}"],
  "rep.m6": ["6 months", "6 ay", "6 месяцев"],
  "rep.m12": ["12 months", "12 ay", "12 месяцев"],
  "rep.period": ["Period", "Dövr", "Период"],
  "rep.by_category": ["By category", "Kateqoriya üzrə", "По категориям"],
  "rep.vendors": ["Top vendors", "Əsas satıcılar", "Основные поставщики"],
  "rep.none": ["No invoices in this period.", "Bu dövrdə faktura yoxdur.", "За этот период счетов нет."],
  "rep.c_month": ["Month", "Ay", "Месяц"],
  "rep.c_amount": ["Amount, {cur}", "Məbləğ, {cur}", "Сумма, {cur}"],
  "rep.error": ["The report couldn't be loaded.", "Hesabat yüklənmədi.", "Не удалось загрузить отчёт."],
  "cat.Travel - Accommodation": ["Travel - Accommodation", "Səfər - Yaşayış", "Поездки - Проживание"],
  "cat.Meals & Entertainment": ["Meals & Entertainment", "Yemək və qonaqlıq", "Питание и представительские"],
  "cat.Software & Subscriptions": ["Software & Subscriptions", "Proqram təminatı və abunələr", "ПО и подписки"],

  // ---------------------------------------------------------------- employees (audit team)
  "emp.lede": [
    "Everyone with an account and what they have submitted. Select a person to see their spending by month and their invoices.",
    "Hesabı olan hər kəs və göndərdikləri. Aylıq xərcini və fakturalarını görmək üçün şəxsi seçin.",
    "Все, у кого есть учётная запись, и что они отправили. Выберите человека, чтобы увидеть расходы по месяцам и счета.",
  ],
  "emp.c_person": ["Person", "Şəxs", "Человек"],
  "emp.c_waiting": ["Waiting", "Gözləyir", "Ждут"],
  "emp.c_last": ["Last invoice", "Son faktura", "Последний счёт"],
  "emp.pick": [
    "Select a person on the left to see their report.",
    "Hesabatı görmək üçün soldan şəxsi seçin.",
    "Выберите человека слева, чтобы увидеть отчёт.",
  ],
  "emp.their": ["Their invoices", "Fakturaları", "Счета"],
  "emp.none": ["No invoices yet.", "Hələ faktura yoxdur.", "Счетов пока нет."],
  "emp.loading": ["Loading…", "Yüklənir…", "Загружаем…"],
  "emp.error": ["The list couldn't be loaded.", "Siyahı yüklənmədi.", "Не удалось загрузить список."],
  "ov.all_people": ["All employees", "Bütün işçilər", "Все сотрудники"],

  // ---------------------------------------------------------------- filters and paging
  "pager.label": ["Pages", "Səhifələr", "Страницы"],
  "pager.prev": ["Previous", "Əvvəlki", "Назад"],
  "pager.next": ["Next", "Növbəti", "Вперёд"],
  "pager.range": ["{from}–{to} of {total}", "{from}–{to} / {total}", "{from}–{to} из {total}"],
  "filter.all": ["All", "Hamısı", "Все"],
  "filter.currency": ["Currency", "Valyuta", "Валюта"],
  "filter.from": ["Submitted from", "Göndərilmə tarixi, başlanğıc", "Отправлен с"],
  "filter.to": ["to", "son", "по"],
  "filter.clear": ["Clear filters", "Filtrləri təmizlə", "Сбросить фильтры"],
  "filter.role": ["Role", "Rol", "Роль"],
  "filter.status": ["Status", "Vəziyyət", "Статус"],
  "filter.people": ["Search by name or email", "Ad və ya e-poçt üzrə axtar", "Поиск по имени или почте"],
  "filter.invoices": ["Search by vendor or invoice number", "Satıcı və ya faktura nömrəsi üzrə axtar", "Поиск по поставщику или номеру счёта"],
  "filter.none": ["Nothing matches these filters.", "Bu filtrlərə uyğun heç nə yoxdur.", "По этим фильтрам ничего не найдено."],
  "filter.active": ["Active", "Aktiv", "Активные"],
  "filter.inactive": ["Deactivated", "Deaktiv", "Отключённые"],
  "filter.with_invoices": ["With invoices", "Fakturası olanlar", "Со счетами"],

  // ---------------------------------------------------------------- assistant
  "chat.title": ["Assistant", "Köməkçi", "Помощник"],
  "chat.sub": ["Policy, planned expenses, your invoices", "Siyasət, planlaşdırılan xərc, fakturalarınız", "Политика, планы расходов, ваши счета"],
  "chat.open": ["Open the assistant", "Köməkçini aç", "Открыть помощника"],
  "chat.clear": ["Start over", "Yenidən başla", "Начать заново"],
  "chat.send": ["Send", "Göndər", "Отправить"],
  "chat.placeholder": ["Ask about a limit, an expense or an invoice…", "Limit, xərc və ya faktura haqqında soruşun…", "Спросите о лимите, расходе или счёте…"],
  "chat.thinking": ["The assistant is answering", "Köməkçi cavab yazır", "Помощник отвечает"],
  "chat.error": ["The assistant couldn't answer. Try again.", "Köməkçi cavab verə bilmədi. Yenidən cəhd edin.", "Помощник не смог ответить. Попробуйте ещё раз."],
  "chat.hello": [
    "Hi {name}. Ask me about the expense policy, check a planned expense (for example \"hotel 900 AZN 2 nights\"), or ask about your invoices (\"why #4\").",
    "Salam, {name}. Xərc siyasəti haqqında soruşun, planlaşdırdığınız xərci yoxlayın (məsələn \"otel 900 AZN 2 gecə\") və ya fakturanız barədə soruşun (\"#4 niyə\").",
    "Здравствуйте, {name}. Спросите о политике расходов, проверьте планируемый расход (например «отель 900 AZN 2 ночи») или узнайте о своём счёте («почему #4»).",
  ],
  "chat.s1": ["Hotel limit", "Otel limiti", "Лимит на отель"],
  "chat.s2": ["Software 650 USD", "Proqram 650 USD", "ПО 650 USD"],
  "chat.s3": ["My invoices", "Fakturalarım", "Мои счета"],
  "chat.s4": ["Which currencies?", "Hansı valyutalar?", "Какие валюты?"],

  "chat.hi": ["Hi {name}, how can I help?", "Salam, {name}. Nə ilə kömək edim?", "Здравствуйте, {name}. Чем помочь?"],
  "chat.lead": [
    "I answer from the company's expense policy and your own invoices. Pick a topic or just type.",
    "Şirkətin xərc siyasəti və öz fakturalarınız əsasında cavab verirəm. Mövzu seçin və ya sadəcə yazın.",
    "Отвечаю по политике расходов компании и вашим счетам. Выберите тему или просто напишите.",
  ],
  "chat.c1": ["Check an expense before you pay", "Xərci ödəməzdən əvvəl yoxla", "Проверить расход до оплаты"],
  "chat.c1d": ["Limits, conversion and who has to approve", "Limitlər, məzənnə və kimin təsdiqi lazımdır", "Лимиты, пересчёт и кто согласует"],
  "chat.c1q": ["Hotel 900 AZN 2 nights", "Otel 900 AZN 2 gecə", "Отель 900 AZN 2 ночи"],
  "chat.c1a": ["Hotel 900 AZN 2 nights", "Otel 900 AZN 2 gecə", "Отель 900 AZN 2 ночи"],
  "chat.c2": ["How much may I spend?", "Nə qədər xərcləyə bilərəm?", "Сколько можно потратить?"],
  "chat.c2d": ["The most that stays inside the limit", "Limit daxilində qalan ən yüksək məbləğ", "Максимум в пределах лимита"],
  "chat.c2q": ["Max for hotel, 3 nights", "Otel üçün maks, 3 gecə", "Максимум на отель, 3 ночи"],
  "chat.c3": ["My spending", "Xərclərim", "Мои расходы"],
  "chat.c3d": ["Totals, categories and the state of each invoice", "Cəmlər, kateqoriyalar və hər fakturanın vəziyyəti", "Итоги, категории и статус каждого счёта"],
  "chat.c3q": ["Spending by category", "Kateqoriya üzrə xərcim", "Расходы по категориям"],
  "chat.c3a_t": ["The audit desk", "Audit masası", "Стол аудита"],
  "chat.c3a_d": ["The queue, top spenders, most broken rules", "Növbə, ən çox xərcləyənlər, ən çox pozulan qaydalar", "Очередь, кто тратит больше, частые нарушения"],
  "chat.c3a": ["Who spends the most?", "Ən çox kim xərcləyib?", "Кто тратит больше всех?"],
  "chat.tone_ok": ["Within policy", "Siyasətə uyğundur", "В рамках политики"],
  "chat.tone_warn": ["Needs attention", "Diqqət tələb edir", "Требует внимания"],
  "chat.tone_bad": ["Breaks a rule", "Qayda pozulur", "Нарушает правило"],
  "chat.bigger": ["Make it bigger", "Böyüt", "Увеличить"],
  "chat.smaller": ["Make it smaller", "Kiçilt", "Уменьшить"],
  "chat.foot": [
    "Answers come from the policy rules. The assistant never approves or rejects anything.",
    "Cavablar siyasət qaydalarından gəlir. Köməkçi heç nəyi təsdiqləmir və ya rədd etmir.",
    "Ответы основаны на правилах политики. Помощник ничего не одобряет и не отклоняет.",
  ],
};
